sudo: required
language: java
jdk: oraclejdk8

env:
  global:
  - secure: "encrypted-sonar-token"
  - secure: "encrypted-heroku-api-key"

addons:
  sonarcloud:
    organization: "tonikolaba-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar


deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: spring-vuejsxstarter
